Fix sign-compare error
Newer GCCs will fail comparing a `__time_t` with an unsigned int on i686; do the necessary type coercion since we know this will be safe rather than having to use `__time_t` everywhere (its implementation is arch-specific anyway).

```
psi-notify.c: In function 'suspend_for_remaining_interval':
psi-notify.c:546:26: error: comparison of integer expressions of different signedness: '__time_t' {aka 'long int'} and 'unsigned int' [-Werror=sign-compare]
  546 |     if (remaining.tv_sec >= cfg.update_interval) {
      |                          ^~
cc1: all warnings being treated as errors
```

see the Fedora scratch builds:

  https://koji.fedoraproject.org/koji/taskinfo?taskID=44743766

it succeeds on x86_64, fails on i686:

  https://kojipkgs.fedoraproject.org//work/tasks/3799/44743799/build.log

Fixed scratch builds:

  https://koji.fedoraproject.org/koji/taskinfo?taskID=44745335

(it errors out now on s390x, but our s390x builder is a bit flaky and even if it is a real issue it seesms unrelated)

Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>